name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    env:
      HEADLESS: true

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js dependencies
        run: npm install

      - name: Browser Tests
        run: xvfb-run --auto-servernum npm test

      - name: Archive Code Coverage Report
        continue-on-error: true
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Code Coverage Report
          path: reports/

      - name: Cleanup after xvfb
        uses: bcomnes/cleanup-xvfb@v1.0.8

      - name: Security Audit
        run: npm audit --omit dev

      - name: Lint Code
        run: npm run lint
